# Generated by Django 5.0.1 on 2024-05-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotechcollect', '0002_alter_feedback_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('smartphone', 'Smartphone'), ('laptop', 'Laptop'), ('television', 'Television'), ('pcparts', 'PC Parts'), ('radio', 'Radio'), ('musicplayer', 'Music Player'), ('camera', 'Camera'), ('ac', 'Air conditioners'), ('other', 'Other')], max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('working', 'Working'), ('non-working', 'Non-Working')], max_length=12)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PickupDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('pickup_time', models.DateTimeField()),
                ('special_instructions', models.TextField(blank=True)),
            ],
        ),
    ]
